kind: pipeline
name: build-and-deploy

platform:
  os: linux
  arch: amd64

steps:
  - name: download-hugo
    image: docker:git
    commands:
      - git clone https://github.com/gohugoio/hugo hugo-src
      - cd hugo-src && git checkout $(cat ../version)
  - name: build-hugo-extended
    image: golang:1.13
    commands: 
      - (cd hugo-src && go build -o hugo --tags extended main.go)
      - (cd hugo-src && ../tags.sh -extended) > .tags
    volumes:
      - name: GOPATH
        path: /go
    environment:
      GO111MODULE: on
      GOARCH: amd64
      GOOS: linux
      GOPROXY: https://proxy.golang.org,direct
  - name: build-and-deploy-extended-image
    image: plugins/docker
    settings:
      dockerfile: extended.Dockerfile
      repo: garykim/hugo
      username: garykim
      password:
        from_secret: docker_password
  - name: build-hugo-standard
    image: golang:1.13
    commands: 
      - (cd hugo-src && go build -o hugo main.go)
      - (cd hugo-src && ../tags.sh) > .tags
    volumes:
      - name: GOPATH
        path: /go
    environment:
      GO111MODULE: on
      GOARCH: amd64
      GOOS: linux
      GOPROXY: https://proxy.golang.org,direct
  - name: build-and-deploy-standard-image
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: garykim/hugo
      username: garykim
      password:
        from_secret: docker_password

volumes:
  - name: GOPATH
    temp: {}

---
kind: secret
name: docker_password
data: ozVISJhAz51QIczo6H4EIkNUDEzDzoT4oHeKJEdFL5eFAGcLigTiQpui8E4g0yEVfQ==
